// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzB6EBkAenCuURUXDoji7N67xjDTb8SI',
    appId: '1:728196948525:web:3b704163e1b3a804f4cea4',
    messagingSenderId: '728196948525',
    projectId: 'beeguard-smartbee',
    authDomain: 'beeguard-smartbee.firebaseapp.com',
    databaseURL: 'https://beeguard-smartbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beeguard-smartbee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWR4GYM3caA2xrRoYIxyaS-MGfMEu5bM',
    appId: '1:728196948525:ios:9c979f23255a34c9f4cea4',
    messagingSenderId: '728196948525',
    projectId: 'beeguard-smartbee',
    databaseURL: 'https://beeguard-smartbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beeguard-smartbee.firebasestorage.app',
    iosBundleId: 'com.example.beeguard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJWR4GYM3caA2xrRoYIxyaS-MGfMEu5bM',
    appId: '1:728196948525:ios:9c979f23255a34c9f4cea4',
    messagingSenderId: '728196948525',
    projectId: 'beeguard-smartbee',
    databaseURL: 'https://beeguard-smartbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beeguard-smartbee.firebasestorage.app',
    iosBundleId: 'com.example.beeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqzB6EBkAenCuURUXDoji7N67xjDTb8SI',
    appId: '1:728196948525:web:2a34aee450a1999df4cea4',
    messagingSenderId: '728196948525',
    projectId: 'beeguard-smartbee',
    authDomain: 'beeguard-smartbee.firebaseapp.com',
    databaseURL: 'https://beeguard-smartbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beeguard-smartbee.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFEUuj2ApVA1bXpe3U88Y1kRmMp3iVng4',
    appId: '1:728196948525:android:b712a97bc2a90ea2f4cea4',
    messagingSenderId: '728196948525',
    projectId: 'beeguard-smartbee',
    databaseURL: 'https://beeguard-smartbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'beeguard-smartbee.firebasestorage.app',
  );
}
